version: '3.8'

services:
  app:
    build: .
    restart: always
    container_name: hauichatbot-app
    depends_on:
      - qdrant
    ports:
      - "8000:8000"
    env_file:
      - app/.env
    environment:
      - LANGCHAIN_ENDPOINT=https://api.smith.langchain.com
      - LANGCHAIN_TRACING_V2=true
      - LANGCHAIN_API_KEY=${LANGCHAIN_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_CHAT_MODEL=${OPENAI_CHAT_MODEL}
      - OPENAI_EMBEDDING_MODEL=${OPENAI_EMBEDDING_MODEL}
#      - QDRANT_HOST=qdrant
#      - QDRANT_PORT=6333
    volumes:
      - ./app:/app
      - ./qdrant_data:/app/qdrant_data
    networks:
      - hauichatbot-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    container_name: hauichatbot-qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_data:/qdrant/storage
    networks:
      - hauichatbot-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  hauichatbot-network:
    driver: bridge
